export const WMO_MAP: Record<number, { condition: string; icon: string }> = {
    0:  { condition: 'Clear',              icon: '01d' },
    1:  { condition: 'Mostly Clear',       icon: '01d' },
    2:  { condition: 'Partly Cloudy',      icon: '02d' },
    3:  { condition: 'Overcast',           icon: '04d' },
    45: { condition: 'Foggy',              icon: '03d' },
    48: { condition: 'Foggy',              icon: '03d' },
    51: { condition: 'Drizzle',            icon: '09d' },
    53: { condition: 'Drizzle',            icon: '09d' },
    55: { condition: 'Drizzle',            icon: '09d' },
    61: { condition: 'Rain',               icon: '10d' },
    63: { condition: 'Rain',               icon: '10d' },
    65: { condition: 'Heavy Rain',         icon: '10d' },
    71: { condition: 'Snow',               icon: '13d' },
    73: { condition: 'Snow',               icon: '13d' },
    75: { condition: 'Heavy Snow',         icon: '13d' },
    77: { condition: 'Snow Grains',        icon: '13d' },
    80: { condition: 'Rain Showers',       icon: '09d' },
    81: { condition: 'Rain Showers',       icon: '09d' },
    82: { condition: 'Heavy Showers',      icon: '09d' },
    85: { condition: 'Snow Showers',       icon: '13d' },
    86: { condition: 'Heavy Snow Showers', icon: '13d' },
    95: { condition: 'Thunderstorm',       icon: '11d' },
    96: { condition: 'Thunderstorm',       icon: '11d' },
    99: { condition: 'Thunderstorm',       icon: '11d' },
};